name: d-8-cwi
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: d8cwi
  id: f3a5f3c2-9f22-48ac-b6b3-99d9f384a163
  drush: 9.7.2
  php: '7.2'
events:
  post-db-import:
    - appserver: cd $LANDO_MOUNT && composer install
services:
  appserver:
    overrides:
      environment:
        BEHAT_PARAMS: >-
          {"extensions" : {"Behat\\MinkExtension" : {"base_url" :
          "http://nginx/"}, "Drupal\\DrupalExtension" : {"drush" :   {
          "root":  "/app/web" }}}}
    config:
      conf: config/php/php.ini
  d7db:
    type: mariadb
    creds:
      user: drupal7db
      password: drupal7db
      database: drupal7db
    portforward: true
tooling:
  phplint:
    service: appserver
    cmd: /app/vendor/bin/phplint
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat
  drush:
    cmd:
      - "drush --root=/app/web"
